#!/usr/bin/python


from mininet.net import Mininet
from minitop import LTBnet
from mininet.cli import CLI
from mininet.log import setLogLevel, info, error


"""Testing script for checking network Topologies"""

if __name__ == '__main__':
    setLogLevel('info')
    hostnames = ['hPMU', 'hPDC']
    hostports = ['enp4s0f0', 'enp4s0f1']
    switchnames = ['s1', 's2']
    portsw = {1: ('enp4s0f0', 's1'), 2: ('enp4s0f1', 's2')}
    linkset = {1: {'setting': {'bw': 10, 'delay': '5ms', 'loss': 10,
                               'max_queue_size': 100, 'use_htb': True},
                   'l1': 'hPMU', 'l2': 's1'},
               2: {'setting': {'bw': 10, 'delay': '5ms', 'loss': 10,
                               'max_queue_size': 100, 'use_htb': True},
                   'l1': 'hPDC', 'l2': 's2'},
               3: {'setting': {'bw': 10, 'delay': '5ms', 'loss': 10,
                               'max_queue_size': 100, 'use_htb': True},
                   'l1': 's1', 'l2': 's2'}}
    opts = {'hostnames': hostnames, 'hostports': hostports, 'switchnames': switchnames, \
            'link_config': linkset, 'port_to_switch': portsw}

    topo = LTBnet(len(hostnames), opts)
    net = Mininet(topo=topo, ipBase='192.168.99.50')
    topo.con_port(net.switches)
    net.start()
    CLI(net)
    net.stop()

